# Generated by Django 4.2.4 on 2023-08-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='sin nombrar', max_length=300, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='sin descripción', max_length=300, verbose_name='Descripción')),
                ('fecha_de_registro', models.DateField(default='sin fecha', max_length=300, verbose_name='Fecha de registro')),
                ('estatus', models.CharField(default='sin estatus', max_length=300, verbose_name='Estatus')),
            ],
        ),
    ]
