# Generated by Django 4.2.4 on 2023-08-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudes',
            options={'verbose_name': 'Solicitudes', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='titulo',
            field=models.CharField(default='sin nombrar', max_length=300, verbose_name='Titulo'),
        ),
    ]
